spring:
  # DataSource
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/bt-emp-test
    username: sa
    password:

  # H2
  h2:
    console:
      enabled: true
      path: /db_console

  # SQL Initialize
  sql:
    init:
      mode: always
      data-locations: classpath:sql/import.sql

  # Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  # Resource Config
  web:
    resources:
      static-locations: classpath:/static/

# MyBatis
mybatis:
  config-location: classpath:mybatis-config.xml